#!/bin/bash
#
# DESCRIPTION
#	This script sets up the environment to compile code on pcv or release build machine.
#
# INSTRUCTIONS
#	For manual PCV build:
#		1. Change to root directory of source tree
#		2. Set BUILD_VERSION to a numeric value
#
#		Example:
#			export VERSION_BUILD=10001
#			./setEnv
#			./buildPcv 
#
#	For Jenkins release build:
#		Script
#			cd $WORKSPACE
#			export VERSION_BUILD=${BUILD_NUMBER}
#			./setEnv
#			./buildRelease


echo "NextLabs Build Environment Preparation Script (setEnv)"
echo "Specify --help for more information"


#
# Set common environment variables
#

if [ "$ProgramW6432" == "" ]; then
	ENV_OS=x86
	PROGRAM_FILES_X86="C:/Program Files"
else
	ENV_OS=x64
	PROGRAM_FILES_X86="C:/Program Files (x86)"
fi

PROGRAM_FILES_X86_DOS=`cygpath -d "$PROGRAM_FILES_X86"`


#
# Map drives
#
# IMPORTANT: Drive mapping is used to deal with space in directory name such as "Program Files"
# that Cygwin and other programs cannot handle readily.

echo "Drive Mapping Before:"
set -x
subst
net use

if [ ! -d i:/ ]; then
	subst i: "$PROGRAM_FILES_X86_DOS\\InstallShield\\2010 StandaloneBuild"
fi

# When running in Tomcat as SYSTEM user, s:/ is mapped to \\nextlabs.com\share instead of \\nextlabs.com\share\data.
# Drive mapping may be done using subst or net use. It needs to be deleted using the correct command.
# The output from subst may look like the following when mapped using subst. Mapping will not
# be shown if mapped using net use. Similarly, net use does not show mappings done using subst.
#	S:\: => UNC\nextlabs.com\share\data

FOUND_IN_SUBST=$(subst | fgrep -q -i "S:"; echo $?;)
FOUND_IN_NET_USE=$(net use | fgrep -q -i "S:"; echo $?;)

if [ "$BUILD_WITHOUT_S_DRIVE" == "" ] || [ $BUILD_WITHOUT_S_DRIVE -eq 0 ]; then
	if [ $FOUND_IN_SUBST -eq 0 ]; then
		subst s: /D
	fi
	
	if [ $FOUND_IN_NET_USE -eq 0 ]; then
		net use s: /delete
	fi

	net use s: "\\\\nextlabs.com\\share\\data"
fi
set +x

echo "Drive Mapping After:"
set -x
subst
net use
set +x

#
# Set build environment variables
#

export NLBUILDROOT=$(cygpath -m $(pwd))

alias dev='cd $NLBUILDROOT'

#
# Print message
#

echo ""
echo "-------------------------------------------------------------------------"
echo "IMPORTANT: You must source this script in a Bash shell to setup the environment."
echo "Invoking ./setEnv will create a new child shell process and the script will"
echo "run in the child process. Changes to the environment is limited to the child"
echo "process, parent process is not affected. The command you should run is:"
echo "  source ./setEnv"
echo "-------------------------------------------------------------------------"
